server:
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  api_key: "test-key"

parser:
  max_concurrent_jobs: 3
  progress_interval: "5s"
  max_demo_size: 1073741824  # 1GB in bytes
  temp_dir: "/tmp/parser-service"

batch:
  gunfight_events_size: 100
  grenade_events_size: 50
  damage_events_size: 200
  round_events_size: 100
  retry_attempts: 3
  retry_delay: "1s"
  http_timeout: "30s"

logging:
  level: "info"
  format: "json"
  file: "logs/service.log"
  error_file: "logs/errors.log"

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "root"
  dbname: "top-frag-parser"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 100
  cleanup_on_finish: true
