name: PHP Unit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  php-unit-tests:
    runs-on: ubuntu-latest
    name: PHP Unit Tests with Coverage

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, sqlite3, gd, exif, zip, curl, fileinfo, soap, dom, xmlreader, xmlwriter, tokenizer, xml, simplexml, phar, session, filter, hash, json, openssl, spl, standard, reflection, date, libxml, pcre, zlib, bcmath, calendar, exif, ffi, ftp, gettext, gmp, intl, pcntl, shmop, snmp, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, xmlrpc, xsl, zend-opcache
        coverage: xdebug

    - name: Copy .env
      run: cp .env.example .env
      working-directory: ./web-app

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ./web-app

    - name: Generate key
      run: php artisan key:generate
      working-directory: ./web-app

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./web-app

    - name: Execute tests with coverage
      run: vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-html=coverage-html
      working-directory: ./web-app

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: php-unit-coverage
        path: |
          ./web-app/coverage.xml
          ./web-app/coverage-html/
        retention-days: 30 