name: PHP Benchmark

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  php-benchmark:
    runs-on: ubuntu-latest
    name: PHP Benchmark

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, sqlite3, gd, exif, zip, curl, fileinfo, soap, dom, xmlreader, xmlwriter, tokenizer, xml, simplexml, phar, session, filter, hash, json, openssl, spl, standard, reflection, date, libxml, pcre, zlib, bcmath, calendar, exif, ffi, ftp, gettext, gmp, intl, pcntl, shmop, snmp, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, xmlrpc, xsl, zend-opcache

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ./backend

    - name: Configure SQLite for PHPBench
      run: |
        cp .env.phpbench .env
        touch database/database.sqlite
      working-directory: ./backend

    - name: Generate key
      run: php artisan key:generate
      working-directory: ./backend

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./backend

    - name: Run PHPBench benchmarks with HTML output
      run: |
        export DB_CONNECTION=sqlite
        export DB_DATABASE=:memory:
        export APP_ENV=phpbench
        export LARAVEL_DISABLE_ERROR_HANDLER=1
        
        echo "=== RUNNING PHPBENCH ==="
        # Run PHPBench directly with maximum error suppression
        php -d error_reporting=0 vendor/bin/phpbench run benchmarks/ --report=aggregate --output=html --tolerate-failure || true
        
        echo "=== CHECKING FOR OUTPUT ==="
        ls -la .phpbench/ || echo "No .phpbench directory"
        ls -la .phpbench/html/ || echo "No html directory"
        
        echo "=== SUCCESS ==="
      working-directory: ./backend

    - name: Upload benchmark artifacts
      uses: actions/upload-artifact@v4
      with:
        name: php-benchmark-results
        path: |
          ./backend/.phpbench/
          ./backend/.phpbench/html/
          ./backend/*.html
        retention-days: 30 