name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: cd parser-service && go mod download

    - name: Run tests
      run: cd parser-service && go test -v -cover

    - name: Run tests with coverage report
      run: cd parser-service && go test -coverprofile=coverage.out

    - name: Display coverage
      run: cd parser-service && go tool cover -func=coverage.out 